"""add color icon_emoji is_starred to file_records

Revision ID: b5c9ce40ba1e
Revises: fc9f7279957d
Create Date: 2026-08-17 16:36:32.569401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5c9ce40ba1e'
down_revision: Union[str, Sequence[str], None] = 'fc9f7279957d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_access_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_access_logs_file_id'), 'file_access_logs', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_access_logs_user_id'), 'file_access_logs', ['user_id'], unique=False)
    op.create_table('file_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('shared_with_user_id', sa.Uuid(), nullable=True),
    sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('permission_level', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_shares_file_id'), 'file_shares', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_shares_share_token'), 'file_shares', ['share_token'], unique=False)
    op.add_column('file_records', sa.Column('is_starred', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_file_records_is_starred'), 'file_records', ['is_starred'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_records_is_starred'), table_name='file_records')
    op.drop_column('file_records', 'is_starred')
    op.drop_index(op.f('ix_file_shares_share_token'), table_name='file_shares')
    op.drop_index(op.f('ix_file_shares_file_id'), table_name='file_shares')
    op.drop_table('file_shares')
    op.drop_index(op.f('ix_file_access_logs_user_id'), table_name='file_access_logs')
    op.drop_index(op.f('ix_file_access_logs_file_id'), table_name='file_access_logs')
    op.drop_table('file_access_logs')
    # ### end Alembic commands ###
