"""add color icon_emoji is_starred to file_records

Revision ID: b5c9ce40ba1e
Revises: fc9f7279957d
Create Date: 2026-08-17 16:36:32.569401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5c9ce40ba1e'
down_revision: Union[str, Sequence[str], None] = 'fc9f7279957d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.tables "
            "WHERE table_schema='public' AND table_name=:t)"
        ),
        {"t": table_name},
    )
    return result.scalar()


def _column_exists(table_name: str, column_name: str) -> bool:
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
            "WHERE table_schema='public' AND table_name=:t AND column_name=:c)"
        ),
        {"t": table_name, "c": column_name},
    )
    return result.scalar()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('file_access_logs'):
        op.create_table('file_access_logs',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('file_id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
            sa.Column('accessed_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('file_access_logs') or True:
        # indexes: safe to skip if already exist via IF NOT EXISTS workaround
        pass
    conn = op.get_bind()
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_file_access_logs_file_id ON file_access_logs (file_id)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_file_access_logs_user_id ON file_access_logs (user_id)"
    ))

    if not _table_exists('file_shares'):
        op.create_table('file_shares',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('file_id', sa.Uuid(), nullable=False),
            sa.Column('owner_id', sa.Uuid(), nullable=False),
            sa.Column('shared_with_user_id', sa.Uuid(), nullable=True),
            sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
            sa.Column('permission_level', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ),
            sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_file_shares_file_id ON file_shares (file_id)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_file_shares_share_token ON file_shares (share_token)"
    ))

    if _table_exists('file_records') and not _column_exists('file_records', 'is_starred'):
        op.add_column('file_records', sa.Column('is_starred', sa.Boolean(), nullable=False, server_default=sa.false()))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_file_records_is_starred ON file_records (is_starred)"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists('file_records') and _column_exists('file_records', 'is_starred'):
        op.drop_index(op.f('ix_file_records_is_starred'), table_name='file_records')
        op.drop_column('file_records', 'is_starred')
    if _table_exists('file_shares'):
        op.drop_index(op.f('ix_file_shares_share_token'), table_name='file_shares')
        op.drop_index(op.f('ix_file_shares_file_id'), table_name='file_shares')
        op.drop_table('file_shares')
    if _table_exists('file_access_logs'):
        op.drop_index(op.f('ix_file_access_logs_user_id'), table_name='file_access_logs')
        op.drop_index(op.f('ix_file_access_logs_file_id'), table_name='file_access_logs')
        op.drop_table('file_access_logs')
    # ### end Alembic commands ###
